obj-m := ramdisk.o
ramdisk-objs := ramdisk.rust.o macro_wrapper.o

CARGO ?= cargo

export c_flags

$(src)/target/x86_64-linux-kernel/debug/libramdisk.a: cargo_will_determine_dependencies
	cd $(src); $(CARGO) build --lib -Z build-std=core,alloc --target=x86_64-linux-kernel

.PHONY: cargo_will_determine_dependencies

%.rust.o: target/x86_64-linux-kernel/debug/lib%.a
	$(LD) -r -o $@ --whole-archive $<
